export const statuses = [
  "No send",
  "No Send",
  "New",
  "Potential",
  "No answer",
  "No money",
  "Deposited",
  "Wrong info",
  "Wrong number",
  "Wrong country",
  "Not interested",
  "Callback",
  "Duplicate",
  "System duplicate",
  "Test",
];
